# Calculation of the bicubic interpolation coefficients

This notebook calculates the coefficients for a bicubic interpolation.
It is just a simple linear transformation.
The result wil be a 16x16 matrix

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## Define the polynomials for the function and his derivatives

In [2]:
def ff(x,y,mat):
    for i in range(4):
        for j in range(4):
            mat[i,j]=(x**i)*(y**j)
            
    return mat

In [3]:
def ffx(x,y,mat):
    for i in range(1,4):
        for j in range(4):
            mat[i,j]=i*(x**(i-1))*(y**j)
            
    return mat

In [4]:
def ffy(x,y,mat):
    for i in range(4):
        for j in range(1,4):
            mat[i,j]=j*(x**i)*(y**(j-1))
            
    return mat

In [5]:
def ffxy(x,y,mat):
    for i in range(1,4):
        for j in range(1,4):
            mat[i,j]=i*j*(x**(i-1))*(y**(j-1))
            
    return mat

## Define the points in the grid square

The order of the points are counterclock-wise on a square.

In [6]:
hh = zeros((16,16))
points = [[0,0],[1,0],[1,1],[0,1]]

## Prepare the matrix

In [7]:
for l in range(4):
    hs = zeros((4,4))
    x = points[l][0]
    y = points[l][1]
    # We call the function
    ff(x,y,hs)
    hh[l,:] = hs.reshape(1,16)

In [8]:
for l in range(4,8):
    hs = zeros((4,4))
    x = points[l-4][0]
    y = points[l-4][1]
    # We call the function
    ffx(x,y,hs)
    hh[l,:] = hs.reshape(1,16)

In [9]:
for l in range(8,12):
    hs = zeros((4,4))
    x = points[l-8][0]
    y = points[l-8][1]
    # We call the function
    ffy(x,y,hs)
    hh[l,:] = hs.reshape(1,16)

In [10]:
for l in range(12,16):
    hs = zeros((4,4))
    x = points[l-12][0]
    y = points[l-12][1]
    # We call the function
    ffxy(x,y,hs)
    hh[l,:] = hs.reshape(1,16)

In [11]:
print hh

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  2.  3.  0.  1.  2.  3.  0.  1.  2.  3.  0.  1.  2.  3.]
 [ 0.  1.  2.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  2.  3.  0.  2.  4.  6.  0.  3.  6. 

In [12]:
# Check the determinant (must be one)
det(hh)

1.0

## Invert the matrix. That's the one we are looking for.

In [13]:
hhinv = inv(hh)

In [14]:
print hhinv

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [-3. -0. -0.  3. -0. -0. -0. -0. -2. -0. -0. -1. -0. -0. -0. -0.]
 [ 2.  0.  0. -2.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [-0. -0. -0. -0. -3. -0. -0.  3. -0. -0. -0. -0. -2. -0. -0. -1.]
 [-0. -0. -0. -0.  2. -0. -0. -2. -0. -0. -0. -0.  1. -0. -0.  1.]
 [-3.  3.  0.  0. -2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0. -0. -0. -0. -0. -0. -0. -3.  3. -0. -0. -2. -1. -0. -0.]
 [ 9. -9.  9. -9.  6.  3. -3. -6.  6. -6. -3.  3.  4.  2.  1.  2.]
 [-6.  6. -6.  6. -4. -2.  2.  4. -3.  3.  3. -3. -2. -1. -1. -2.]
 [ 2. -2.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2. -2.  0.  0.  1.  1.  0.  0.]
 [-6.  6. -6.  6. -3. -3.  3.  3. -4.  4.  2. -2. -2. -2. -1. 

In [15]:
savetxt('bicoeffs.dat',transpose(hhinv),fmt='%d',delimiter=',')